name: Run tests

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: >-
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

      - name: Build project
        run: >-
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
          --target Test_template_library
          --target Test_Rect
          --target Test_Bundle
          --target Test_Activity

      - name: Test template library
        run: ${{github.workspace}}/build/test/Test_template_library

      - name: Test Rect
        run: ${{github.workspace}}/build/test/Test_Rect

      - name: Test Bundle
        run: ${{github.workspace}}/build/test/Test_Bundle

      - name: Test Activity
        run: ${{github.workspace}}/build/test/Test_Activity
