name: Run tests

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        --target Test_template_library -D CMAKE_C_COMPILER=clang -D CMAKE_CXX_COMPILER=clang++
