name: Run tests

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: >-
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
          --target Test_template_library -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
